# It can control creeper explosions.
creeper_explosion:
  enabled: true
  change-cooldown: 0
  default-value: true
  mode: EXPERT
  type: SETTING

# It can control wither explosions.
wither_explosion:
  enabled: true
  change-cooldown: 0
  default-value: true
  mode: EXPERT
  type: SETTING

# It can control phantom spawning.
phantom_spawning:
  enabled: true
  change-cooldown: 0
  default-value: true
  mode: EXPERT
  type: SETTING

# It can control witch potion throwing.
# Added since 1.1.0
witch_potion_throwing:
  enabled: true
  change-cooldown: 0
  default-value: true
  mode: EXPERT
  type: SETTING

# It can control windcharge launching.
# Added since 2.0.0
windcharge_launching:
  enabled: true
  change-cooldown: 0
  default-value: true
  mode: EXPERT
  type: SETTING

# It can control ghast fireballs.
# Added since 2.0.0
ghast_fireball:
  enabled: true
  change-cooldown: 0
  default-value: true
  mode: EXPERT
  type: SETTING

# It can control blaze fireballs.
# Added since 2.0.0
blaze_fireball:
  enabled: true
  change-cooldown: 0
  default-value: true
  mode: EXPERT
  type: SETTING


# It can control glow squid spawning.
# Added since 2.0.2
glowsquid_spawning:
  enabled: true
  change-cooldown: 0
  default-value: true
  mode: EXPERT
  type: SETTING