flags:
  creeper_explosion:
    enabled: true
    change-cooldown: 0
    default-value: false
  wither_explosion:
    enabled: true
    change-cooldown: 0
    default-value: false
  phantom_spawning:
    enabled: true
    change-cooldown: 0
    default-value: false